const Comment = require("./comments");
const DifficultyLevel = require("./difficulty_levels");
const Gender = require("./gender");
const Notification = require("./notifications");
const NotificationType = require("./notifications_types");
const Occupation = require("./occupations");
const ProjectTech = require("./project_tech");
const Project = require("./projects");
const ProjectPicture = require("./projects_pictures");
const RequiredTech = require("./required_techs");
const Thread = require("./threads");
const User = require("./users");
const UserLike = require("./users_liked_projects");

User.hasMany(Project, { foreignKey: "user_id" });
Project.belongsTo(User, { foreignKey: "user_id" });
Gender.hasMany(User, { foreignKey: "gender_id" });
User.belongsTo(Gender, { foreignKey: "gender_id" });
Occupation.hasMany(User, { foreignKey: "occupation_id" });
User.belongsTo(Occupation, { foreignKey: "occupation_id" });
DifficultyLevel.hasMany(Project, { foreignKey: "difficulty_level_id" });
Project.belongsTo(DifficultyLevel, { foreignKey: "difficulty_level_id" });

NotificationType.hasMany(Notification, { foreignKey: "type_id" });
Notification.belongsTo(NotificationType, { foreignKey: "type_id" });
Project.belongsToMany(User, { through: UserLike, foreignKey: "liked_project_id", otherKey: "user_id" });
Project.belongsToMany(RequiredTech, { through: ProjectTech, foreignKey: "project_id", otherKey: "tech_id" });
RequiredTech.belongsToMany(Project, { through: ProjectTech, foreignKey: "tech_id", otherKey: "project_id" });
User.belongsToMany(Project, { through: UserLike, foreignKey: "user_id", otherKey: "liked_project_id" });
Notification.belongsTo(Project, { foreignKey: "project_id" });
Project.hasMany(Notification, { foreignKey: "project_id" });
ProjectTech.belongsTo(Project, { foreignKey: "project_id" });
Project.hasMany(ProjectTech, { foreignKey: "project_id" });
ProjectPicture.belongsTo(Project, { foreignKey: "project_id" });
Project.hasMany(ProjectPicture, { foreignKey: "project_id" });
Thread.belongsTo(Project, { foreignKey: "project_id" });
Project.hasMany(Thread, { foreignKey: "project_id" });
UserLike.belongsTo(Project, { foreignKey: "liked_project_id" });
Project.hasMany(UserLike, { foreignKey: "liked_project_id" });
ProjectTech.belongsTo(RequiredTech, { foreignKey: "tech_id" });
RequiredTech.hasMany(ProjectTech, { foreignKey: "tech_id" });
Comment.belongsTo(Thread, { foreignKey: "thread_id" });
Thread.hasMany(Comment, { foreignKey: "thread_id" });
Comment.belongsTo(User, { foreignKey: "user_id" });
User.hasMany(Comment, { foreignKey: "user_id" });
Notification.belongsTo(User, { foreignKey: "acted_user_id" });
User.hasMany(Notification, { foreignKey: "acted_user_id" });
Notification.belongsTo(User, { foreignKey: "notified_user_id" });
User.hasMany(Notification, { foreignKey: "notified_user_id" });
Thread.belongsTo(User, { foreignKey: "user_id" });
User.hasMany(Thread, { foreignKey: "user_id" });
UserLike.belongsTo(User, { foreignKey: "user_id" });
User.hasMany(UserLike, { foreignKey: "user_id" });

module.exports = { RequiredTech, NotificationType, Gender, Occupation, DifficultyLevel, User, Project, Thread, Comment, Notification, ProjectPicture, ProjectTech, UserLike }
